apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ddns
  name: ddns
  namespace: dhcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddns
  template:
    metadata:
      labels:
        app: ddns
    spec:
      containers:
      - image: docker.io/npflan/ddns:2019-weekend3
        imagePullPolicy: Always
        name: ddns
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ddns
  name: ddns
  namespace: default
spec:
  clusterIP: 10.101.128.128
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    app: ddns
  sessionAffinity: None
  type: ClusterIP
