apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: serverteam-dns
  name: serverteam-dns
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: serverteam-dns
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: serverteam-dns
    spec:
      containers:
      - image: docker.io/npflan/serverteam-dns:kube-dns
        imagePullPolicy: Always
        name: serverteam-dns
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: serverteam-dns
  name: serverteam-dns
  namespace: default
spec:
  clusterIP: 10.101.128.128
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    run: serverteam-dns
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}